export const initialData = [
  {
    id: 1,
    title: "Onboarding Call",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 2,
    title: "Google Search Console Access",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 3,
    title: "Google Analytics Access",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 4,
    title: "Website Access",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 5,
    title: "Technical Audit",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 6,
    title: "Anchor Text and Semantic Analysis",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 7,
    title: "Competitor Analysis",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 8,
    title: "Anchor Text / URL Mapping",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 9,
    title: "Google Data Studio Report + Local Reporting Suite",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 10,
    title: "Site Level Optimization",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 11,
    title: "On Page Optimization",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 12,
    title: "Content Creation",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 13,
    title: "Content Publishing",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 14,
    title: "Premium Press Release",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 15,
    title: "Authority Nche Placements",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 16,
    title: "Review Managment",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 17,
    title: "Index Links",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
  {
    id: 18,
    title: "Video Recap",
    n1: "Note 1",
    n2: "Note 2",
    n3: "Note 3",
    n4: "Note 4",
    n5: "Note 5",
  },
];
